
import turtle
wn = turtle.Screen()
wn.bgcolor("cyan")

spot = turtle.Turtle()
spot.right(150)
spot.forward(90)
spot.left(90)
spot.forward(45)
spot.left(90)
spot.forward(150)
spot.right(90)  
spot.forward(15)  
spot.left(90)
spot.forward(35)   
spot.left(45)
spot.forward(20)
spot.right(45)   
spot.forward(60)
spot.right(90)
spot.forward(20)
spot.left(90)
spot.forward(10)
spot.left(55)    
spot.forward(30)       
spot.right(30)                              
spot.forward(35)         
spot.left(32)           
spot.forward(2)
spot.left(22)
spot.forward(2)
spot.left(22)
spot.forward(2)
spot.left(22)
spot.forward(2)
spot.left(32)         
spot.forward(35)       
spot.right(30)
spot.forward(30)       
spot.left(55)       
spot.forward(10)
spot.left(90)
spot.forward(20)
spot.right(90)
spot.forward(60)  
spot.right(45)
spot.forward(20)
spot.left(45)
spot.forward(35)
spot.left(90)
spot.forward(15) 
spot.right(90)
spot.forward(60)
#spot.left(90)
#spot.forward(170)
